/** MOCK DATA */
let mockId = 1
const mockSalaryGrade = {
  id: 1, // if your ApiResponseData includes `id`
  nbc_no: 123,
  effective_date: '2024-07-01',
  tranche: 4,
  salary_grade: 12,
  step: 3,
  amount: 34567.89,
}

const mockItemNumber = [
  {
    id: 1,
    number: 'ITEM-000501',
    date_of_creation: '2022-01-01',
    status: 'Filled',
    date_filled_up: '2023-05-15',
    fund_source_id: null,
    employment_status: 'Permanent',
    position: null,
    position_id: null,
  },
  {
    id: 2,
    number: 'ITEM-000501',
    date_of_creation: '2022-01-01',
    status: 'Filled',
    date_filled_up: '2023-05-15',
    fund_source_id: null,
    employment_status: 'Contract of Service',
    position: null,
    position_id: null,
  },
]

const individual_basic_details = [
  {
    id: 1,
    first_name: 'Maria',
    last_name: 'Reyes',
    middle_name: 'Lopez',
    ext_name: null,
    birthday: '1985-08-22',
    sex: 'Female',
    place_of_birth: 'Manila',
    civil_status: 'Married',
    height: 160,
    weight: 55,
    blood_type: 'A+',
    gsis_no: '2233445566',
    pag_ibig_no: '6677889900',
    philhealth_no: '5566778899',
    sss_no: '1122334455',
    tin: '234-567-890',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 2,
    first_name: 'Carlos',
    last_name: 'Garcia',
    middle_name: 'Torres',
    ext_name: null,
    birthday: '1992-11-05',
    sex: 'Male',
    place_of_birth: 'Cebu City',
    civil_status: 'Single',
    height: 175,
    weight: 72,
    blood_type: 'B+',
    gsis_no: '9988776655',
    pag_ibig_no: '1122112211',
    philhealth_no: '2233223322',
    sss_no: '5566778899',
    tin: '345-678-901',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 3,
    first_name: 'Ana',
    last_name: 'Santos',
    middle_name: 'Diaz',
    ext_name: null,
    birthday: '1996-02-10',
    sex: 'Female',
    place_of_birth: 'Davao City',
    civil_status: 'Single',
    height: 165,
    weight: 60,
    blood_type: 'AB+',
    gsis_no: '3344556677',
    pag_ibig_no: '4455667788',
    philhealth_no: '6677889900',
    sss_no: '7788990011',
    tin: '456-789-012',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 4,
    first_name: 'Roberto',
    last_name: 'Tan',
    middle_name: 'Villanueva',
    ext_name: null,
    birthday: '1988-09-30',
    sex: 'Male',
    place_of_birth: 'Baguio City',
    civil_status: 'Married',
    height: 168,
    weight: 70,
    blood_type: 'O-',
    gsis_no: '7766554433',
    pag_ibig_no: '2211334455',
    philhealth_no: '3344556677',
    sss_no: '8899001122',
    tin: '567-890-123',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 5,
    first_name: 'Emily',
    last_name: 'Navarro',
    middle_name: 'Padilla',
    ext_name: null,
    birthday: '1993-03-18',
    sex: 'Female',
    place_of_birth: 'Pasig City',
    civil_status: 'Single',
    height: 158,
    weight: 52,
    blood_type: 'A-',
    gsis_no: '6655443322',
    pag_ibig_no: '9988776655',
    philhealth_no: '7788990011',
    sss_no: '6677889900',
    tin: '678-901-234',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
]

const employee_data = [
  {
    id: 1,
    individual_basic_detail_id: individual_basic_details[0],
    id_number: 'EMP-2025-001',
    item_id: mockItemNumber[0],
    fund_source_id: {
      id: 1,
      name: 'General Fund',
    },
    salary_grade_id: mockSalaryGrade,
    position: 'Administrative Officer III',
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000123',
    office_id: 10,
    division_id: {
      id: 3,
      name: 'FINANCE AND MANAGEMENT DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 5,
      name: 'ACCOUNTING SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 2,
    individual_basic_detail_id: individual_basic_details[1],
    id_number: 'EMP-2025-002',
    item_id: mockItemNumber[1],
    salary_grade_id: mockSalaryGrade,
    position: 'Human Resource Assistant',
    fund_source: {
      id: 2,
      name: 'Special Education Fund',
    },
    agency_employee_no: 'AGY-000124',
    office_id: 11,
    division_id: {
      id: 4,
      name: 'HUMAN RESOURCE DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 6,
      name: 'RECRUITMENT SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 3,
    individual_basic_detail_id: individual_basic_details[2],
    id_number: 'EMP-2025-003',
    item_id: mockItemNumber[0],
    salary_grade_id: mockSalaryGrade,
    position: 'IT Support Specialist',
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000125',
    office_id: 12,
    division_id: {
      id: 5,
      name: 'INFORMATION TECHNOLOGY DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 7,
      name: 'TECHNICAL SUPPORT SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 4,
    individual_basic_detail_id: individual_basic_details[3],
    id_number: 'EMP-2025-004',
    item_id: mockItemNumber[0],
    salary_grade_id: mockSalaryGrade,
    position: 'Records Officer',
    fund_source: {
      id: 3,
      name: 'Trust Fund',
    },
    agency_employee_no: 'AGY-000126',
    office_id: 13,
    division_id: {
      id: 6,
      name: 'ADMINISTRATIVE DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 8,
      name: 'RECORDS SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 5,
    individual_basic_detail_id: individual_basic_details[4],
    id_number: 'EMP-2025-005',
    item_id: mockItemNumber[0],
    salary_grade_id: mockSalaryGrade,
    position: 'Budget Analyst',
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000127',
    office_id: 14,
    division_id: {
      id: 7,
      name: 'BUDGET DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 9,
      name: 'BUDGET MONITORING SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 6,
    individual_basic_detail_id: individual_basic_details[5],
    id_number: 'EMP-2025-006',
    item_id: mockItemNumber[0],
    salary_grade_id: mockSalaryGrade,
    position: 'Procurement Officer',
    fund_source: {
      id: 2,
      name: 'Special Education Fund',
    },
    agency_employee_no: 'AGY-000128',
    office_id: 15,
    division_id: {
      id: 8,
      name: 'SUPPLY AND PROCUREMENT DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 10,
      name: 'SUPPLY SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
]

const payrollDeductions = () => {
  const phic = mockSalaryGrade.amount * 0.0225 // 2.25%
  const pagIbig = 100 // capped at 100
  const gsis = mockSalaryGrade.amount * 0.09 // 9%
  const loan = 3000 // fixed loan amount

  return [
    {
      id: 1,
      amount: phic,
      range: '1st Half',
      deduction_id: {
        id: 10,
        name: 'PHIC Contribution',
        code: 'PH001',
        details: 'Monthly PhilHealth contribution',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
    {
      id: 2,
      amount: pagIbig,
      range: '2nd Half',
      deduction_id: {
        id: 12,
        name: 'Pag-IBIG MPL',
        code: 'PG002',
        details: 'PAG-IBIG monthly deduction',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
    {
      id: 3,
      amount: gsis,
      range: '1st Half',
      deduction_id: {
        id: 2,
        name: 'GSIS EE Share',
        code: 'PG002',
        details: 'PAG-IBIG monthly deduction',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
    {
      id: 4,
      amount: loan,
      range: '2nd Half',
      deduction_id: {
        id: 12,
        name: 'COOP Emergency Loan',
        code: 'PG002',
        details: 'PAG-IBIG monthly deduction',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
  ]
}
const deductions = payrollDeductions()
const total_deductions_1st_half = deductions.filter((d) => d.range === '1st Half').reduce((sum, d) => sum + d.amount, 0)

const total_deductions_2nd_half = deductions.filter((d) => d.range === '2nd Half').reduce((sum, d) => sum + d.amount, 0)

const total_deductions_whole = total_deductions_1st_half + total_deductions_2nd_half
const net_pay = mockSalaryGrade.amount - total_deductions_whole
const amount_earned_1st_half = mockSalaryGrade.amount / 2 - total_deductions_1st_half
const amount_earned_2nd_half = mockSalaryGrade.amount / 2 - total_deductions_2nd_half
const amount_earned_whole = amount_earned_1st_half + amount_earned_2nd_half
export const payrollMockData = [
  {
    id: mockId++,
    period: '2025-05-01, 2025-05-15',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[0],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: mockId++,
    period: '2025-05-16, 2025-05-31',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[1],
    created_at: '2025-07-07',
    updated_at: '2025-07-07',
  },
  {
    id: mockId++,
    period: '2025-06-01, 2025-06-15',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[2],
    created_at: '2025-07-08',
    updated_at: '2025-07-08',
  },
  {
    id: mockId++,
    period: '2025-06-16, 2025-06-30',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[3],
    created_at: '2025-07-09',
    updated_at: '2025-07-09',
  },
  {
    id: mockId++,
    period: '2025-07-01, 2025-07-15',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[4],
    created_at: '2025-07-10',
    updated_at: '2025-07-10',
  },
]

export const compensatorymockData = [
  {
    id: mockId++,
    ctdo_period: '01-31 December 2025',
    ctdo_supervisor_notes: 'Reviewed and approved.',
    ctdo_status: 'for revision',
    rows: [
      {
        id: 6,
        days_of_the_week: 'Monday',
        work_date: '2025-07-01',
        time_start: '7:30',
        time_end: '16:30',
        accomplishment: 'Completed project planning.',
        authorized_claim: 'COC',
      },
      {
        id: 7,
        days_of_the_week: 'Tuesday',
        work_date: '2025-07-02',
        time_start: '09:00',
        time_end: '17:00',
        accomplishment: 'Team meeting and report writing.',
        authorized_claim: 'COC',
      },
      {
        id: 8,
        days_of_the_week: 'Monday',
        work_date: '2025-07-01',
        time_start: '7:30',
        time_end: '16:15',
        accomplishment: 'Completed project planning.',
        authorized_claim: 'COC',
      },
      {
        id: 9,
        days_of_the_week: 'Tuesday',
        work_date: '2025-07-02',
        time_start: '09:10',
        time_end: '14:21',
        accomplishment: 'Team meeting and report writing.',
        authorized_claim: 'COC',
      },
    ],
    created_at: '2025-07-01',
    updated_at: '2025-07-01',
  },
  {
    id: mockId++,
    ctdo_period: '01-31 November 2025',
    ctdo_supervisor_notes: 'Pending approval.',
    ctdo_status: 'for review',
    rows: [
      {
        id: 2,
        days_of_the_week: 'Wednesday',
        work_date: '2025-07-09',
        time_start: '8:12',
        time_end: '18:00',
        accomplishment: 'Client presentation.',
        authorized_claim: 'COC',
      },
      {
        id: 3,
        days_of_the_week: 'Thursday',
        work_date: '2025-07-10',
        time_start: '09:30',
        time_end: '16:00',
        accomplishment: 'Documentation updates.',
        authorized_claim: 'COC',
      },
    ],
    created_at: '2025-07-05',
    updated_at: '2025-07-05',
  },
  {
    id: mockId++,
    ctdo_period: '01-30 October 2025',
    ctdo_supervisor_notes: 'Requires additional documentation.',
    ctdo_status: 'approved',
    rows: [
      {
        id: 4,
        days_of_the_week: 'Friday',
        work_date: '2025-07-18',
        time_start: '08:46',
        time_end: '15:00',
        accomplishment: 'Site inspection.',
        authorized_claim: 'COC',
      },
      {
        id: 5,
        days_of_the_week: 'Saturday',
        work_date: '2025-07-19',
        time_start: '08:27',
        time_end: '15:00',
        accomplishment: 'Site inspection.',
        authorized_claim: 'COC',
      },
    ],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
]

/* Selection of DeductionTypes */
export const deductionTypes = [
  { id: 1, label: 'ACA/ PERA' },
  { id: 2, label: 'GSIS EE Share' },
  { id: 3, label: 'Withholding Tax' },
  { id: 4, label: 'GSIS Emergency Loan' },
  { id: 5, label: 'GSIS Conso Loan' },
  { id: 6, label: 'GFAL' },
  { id: 7, label: 'GSIS Policy Loan' },
  { id: 8, label: 'GSIS MPLite' },
  { id: 9, label: 'GSIS MPL' },
  { id: 10, label: 'PHIC Contribution' },
  { id: 11, label: 'GSIS Computer Loan' },
  { id: 12, label: 'Pag-IBIG MPL' },
  { id: 13, label: 'Pag-IBIG Contribution' },
  { id: 14, label: 'Pag-IBIG II' },
  { id: 15, label: 'Pag-IBIG Cal. Loan' },
  { id: 16, label: 'MBA Contribution' },
  { id: 17, label: 'Pag-IBIG HLoan' },
  { id: 18, label: 'COOP Emergency Loan' },
  { id: 19, label: 'MBA Loan' },
  { id: 20, label: 'COOP Share Capital' },
  { id: 21, label: 'COOP Fast Cash' },
  { id: 22, label: 'COOP Educ Loan' },
  { id: 23, label: 'COOP Regular Loan' },
  { id: 24, label: 'COOP C19 RPL' },
  { id: 25, label: 'COOP AWSPL' },
  { id: 26, label: 'COOP Disaster Loan' },
  { id: 27, label: 'SWEAP Dues' },
  { id: 28, label: 'LBP Loan' },
]
