/** MOCK DATA */
// Remove the global 'let mockId = 1'

const mockSalaryGrade = {
  id: 1,
  nbc_no: 123,
  effective_date: '2024-07-01',
  tranche: 4,
  salary_grade: 12,
  step: 3,
  amount: 34567.89,
}

const individual_basic_details = [
  {
    id: 1,
    first_name: 'Maria',
    last_name: 'Reyes',
    middle_name: 'Lopez',
    ext_name: null,
    birthday: '1985-08-22',
    sex: 'Female',
    place_of_birth: 'Manila',
    civil_status: 'Married',
    height: 160,
    weight: 55,
    blood_type: 'A+',
    gsis_no: '2233445566',
    pag_ibig_no: '6677889900',
    philhealth_no: '5566778899',
    sss_no: '1122334455',
    tin: '234-567-890',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 2,
    first_name: 'Carlos',
    last_name: 'Garcia',
    middle_name: 'Torres',
    ext_name: null,
    birthday: '1992-11-05',
    sex: 'Male',
    place_of_birth: 'Cebu City',
    civil_status: 'Single',
    height: 175,
    weight: 72,
    blood_type: 'B+',
    gsis_no: '9988776655',
    pag_ibig_no: '1122112211',
    philhealth_no: '2233223322',
    sss_no: '5566778899',
    tin: '345-678-901',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 3,
    first_name: 'Ana',
    last_name: 'Santos',
    middle_name: 'Diaz',
    ext_name: null,
    birthday: '1996-02-10',
    sex: 'Female',
    place_of_birth: 'Davao City',
    civil_status: 'Single',
    height: 165,
    weight: 60,
    blood_type: 'AB+',
    gsis_no: '3344556677',
    pag_ibig_no: '4455667788',
    philhealth_no: '6677889900',
    sss_no: '7788990011',
    tin: '456-789-012',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 4,
    first_name: 'Roberto',
    last_name: 'Tan',
    middle_name: 'Villanueva',
    ext_name: null,
    birthday: '1988-09-30',
    sex: 'Male',
    place_of_birth: 'Baguio City',
    civil_status: 'Married',
    height: 168,
    weight: 70,
    blood_type: 'O-',
    gsis_no: '7766554433',
    pag_ibig_no: '2211334455',
    philhealth_no: '3344556677',
    sss_no: '8899001122',
    tin: '567-890-123',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 5,
    first_name: 'Emily',
    last_name: 'Navarro',
    middle_name: 'Padilla',
    ext_name: null,
    birthday: '1993-03-18',
    sex: 'Female',
    place_of_birth: 'Pasig City',
    civil_status: 'Single',
    height: 158,
    weight: 52,
    blood_type: 'A-',
    gsis_no: '6655443322',
    pag_ibig_no: '9988776655',
    philhealth_no: '7788990011',
    sss_no: '6677889900',
    tin: '678-901-234',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
]

const item_id = [
  {
    id: 1,
    number: 'ITEM-501',
    date_of_creation: '2020-01-01',
    status: 'Active',
    date_filled_up: '2020-03-01',
    fund_source_id: 1,
    fund_source: {
      id: 1,
      name: 'General Fund',
      created_at: '2020-01-01',
      updated_at: '2020-01-01',
    },
    employment_status: 'COS',
    position_id: 1,
    position: {
      id: 1,
      title: 'Administrative Officer III',
      parenthetical_title: null,
      level: null,
      created_at: '2020-01-01',
      updated_at: '2020-01-01',
    },
    created_at: '2020-01-01',
    updated_at: '2020-01-01',
  },
  {
    id: 2,
    number: 'ITEM-501',
    date_of_creation: '2020-01-01',
    status: 'Active',
    date_filled_up: '2020-03-01',
    fund_source_id: 1,
    fund_source: {
      id: 1,
      name: 'General Fund',
      created_at: '2020-01-01',
      updated_at: '2020-01-01',
    },
    employment_status: 'Permanent',
    position_id: 2,
    position: {
      id: 2,
      title: 'Administrative Officer IV',
      parenthetical_title: null,
      level: null,
      created_at: '2020-01-01',
      updated_at: '2020-01-01',
    },
    created_at: '2020-01-01',
    updated_at: '2020-01-01',
  },
]
const employee_data = [
  {
    id: 1,
    individual_basic_detail_id: individual_basic_details[0],
    id_number: 'EMP-2025-001',
    item_id: 1,
    salary_grade_id: mockSalaryGrade,
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000123',
    office_id: 10,
    division_id: {
      id: 3,
      name: 'FINANCE AND MANAGEMENT DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 5,
      name: 'ACCOUNTING SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    item: item_id[0],
  },
  {
    id: 2,
    individual_basic_detail_id: individual_basic_details[1],
    id_number: 'EMP-2025-002',
    item_id: 2,
    salary_grade_id: mockSalaryGrade,
    fund_source: {
      id: 2,
      name: 'Special Education Fund',
    },
    agency_employee_no: 'AGY-000124',
    office_id: 11,
    division_id: {
      id: 4,
      name: 'HUMAN RESOURCE DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 6,
      name: 'RECRUITMENT SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    item: item_id[1],
  },
  {
    id: 3,
    individual_basic_detail_id: individual_basic_details[2],
    id_number: 'EMP-2025-003',
    item_id: 1,
    salary_grade_id: mockSalaryGrade,
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000125',
    office_id: 12,
    division_id: {
      id: 5,
      name: 'INFORMATION TECHNOLOGY DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 7,
      name: 'TECHNICAL SUPPORT SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    item: item_id[0],
  },
  {
    id: 4,
    individual_basic_detail_id: individual_basic_details[3],
    id_number: 'EMP-2025-004',
    item_id: 1,
    salary_grade_id: mockSalaryGrade,
    fund_source: {
      id: 3,
      name: 'Trust Fund',
    },
    agency_employee_no: 'AGY-000126',
    office_id: 13,
    division_id: {
      id: 6,
      name: 'ADMINISTRATIVE DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 8,
      name: 'RECORDS SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    item: item_id[1],
  },
  {
    id: 5,
    individual_basic_detail_id: individual_basic_details[4],
    id_number: 'EMP-2025-005',
    item_id: 1,
    salary_grade_id: mockSalaryGrade,
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000127',
    office_id: 14,
    division_id: {
      id: 7,
      name: 'BUDGET DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 9,
      name: 'BUDGET MONITORING SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    item: item_id[0],
  },
]

/* Payroll Computation*/
const payrollDeductions = () => {
  const phic = mockSalaryGrade.amount * 0.0225 // 2.25%
  const pagIbig = 100 // capped at 100
  const gsis = mockSalaryGrade.amount * 0.09 // 9%
  const loan = 3000 // fixed loan amount

  return [
    {
      id: 1,
      amount: phic,
      range: '1st Half',
      deduction_id: {
        id: 10,
        name: 'PHIC Contribution',
        code: 'PH001',
        details: 'Monthly PhilHealth contribution',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
    {
      id: 2,
      amount: pagIbig,
      range: '2nd Half',
      deduction_id: {
        id: 12,
        name: 'Pag-IBIG MPL',
        code: 'PG002',
        details: 'PAG-IBIG monthly deduction',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
    {
      id: 3,
      amount: gsis,
      range: '1st Half',
      deduction_id: {
        id: 2,
        name: 'GSIS EE Share',
        code: 'PG002',
        details: 'PAG-IBIG monthly deduction',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
    {
      id: 4,
      amount: loan,
      range: '2nd Half',
      deduction_id: {
        id: 12,
        name: 'COOP Emergency Loan',
        code: 'PG002',
        details: 'PAG-IBIG monthly deduction',
        created_at: '2025-01-01T00:00:00Z',
        updated_at: '2025-01-01T00:00:00Z',
      },
    },
  ]
}
const deductions = payrollDeductions()
const total_deductions_1st_half = deductions.filter((d) => d.range === '1st Half').reduce((sum, d) => sum + d.amount, 0)
const total_deductions_2nd_half = deductions.filter((d) => d.range === '2nd Half').reduce((sum, d) => sum + d.amount, 0)
const total_deductions_whole = total_deductions_1st_half + total_deductions_2nd_half
const net_pay = mockSalaryGrade.amount - total_deductions_whole
const amount_earned_1st_half = mockSalaryGrade.amount / 2 - total_deductions_1st_half
const amount_earned_2nd_half = mockSalaryGrade.amount / 2 - total_deductions_2nd_half
const amount_earned_whole = amount_earned_1st_half + amount_earned_2nd_half

/* Payroll */
// Use a local mockId for payrollMockData
let payrollMockId = 1
export const payrollMockData = [
  {
    id: payrollMockId++,
    period: '2025-05-01, 2025-05-15',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[0],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
    deleted_at: '2025-07-06',
  },
  {
    id: payrollMockId++,
    period: '2025-05-16, 2025-05-31',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[1],
    created_at: '2025-07-07',
    updated_at: '2025-07-07',
    deleted_at: '2025-07-07',
  },
  {
    id: payrollMockId++,
    period: '2025-06-01, 2025-06-15',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[2],
    created_at: '2025-07-08',
    updated_at: '2025-07-08',
    deleted_at: '2025-07-08',
  },
  {
    id: payrollMockId++,
    period: '2025-06-16, 2025-06-30',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[3],
    created_at: '2025-07-09',
    updated_at: '2025-07-09',
    deleted_at: '2025-07-09',
  },
  {
    id: payrollMockId++,
    period: '2025-07-01, 2025-07-15',
    gross_monthly_salary: mockSalaryGrade.amount.toFixed(2),
    payroll_deduction_id: payrollDeductions(),
    total_deductions_1st_half: total_deductions_1st_half.toFixed(2),
    amount_earned_1st_half: amount_earned_1st_half.toFixed(2),
    total_deductions_2nd_half: total_deductions_2nd_half.toFixed(2),
    amount_earned_2nd_half: amount_earned_2nd_half.toFixed(2),
    total_deductions_whole: total_deductions_whole.toFixed(2),
    amount_earned_whole: amount_earned_whole.toFixed(2),
    net_pay: net_pay.toFixed(2),
    employee_id: employee_data[4],
    created_at: '2025-07-10',
    updated_at: '2025-07-10',
    deleted_at: '2025-07-10',
  },
]
/* Compensatory */
// Use a local mockId for compensatorymockData
let compensatoryMockId = 1
export const compensatorymockData = [
  {
    id: compensatoryMockId++,
    ctdo_period: '01-31 December 2025',
    ctdo_supervisor_notes: 'Reviewed and approved.',
    ctdo_status: 'for revision',
    rows: [
      {
        id: 6,
        days_of_the_week: 'Monday',
        work_date: '2025-07-01',
        time_start: '7:30',
        time_end: '16:30',
        accomplishment: 'Completed project planning.',
        authorized_claim: 'COC',
      },
      {
        id: 7,
        days_of_the_week: 'Tuesday',
        work_date: '2025-07-02',
        time_start: '09:00',
        time_end: '17:00',
        accomplishment: 'Team meeting and report writing.',
        authorized_claim: 'COC',
      },
      {
        id: 8,
        days_of_the_week: 'Monday',
        work_date: '2025-07-01',
        time_start: '7:30',
        time_end: '16:15',
        accomplishment: 'Completed project planning.',
        authorized_claim: 'COC',
      },
      {
        id: 9,
        days_of_the_week: 'Tuesday',
        work_date: '2025-07-02',
        time_start: '09:10',
        time_end: '14:21',
        accomplishment: 'Team meeting and report writing.',
        authorized_claim: 'COC',
      },
    ],
    created_at: '2025-07-01',
    updated_at: '2025-07-01',
  },
  {
    id: compensatoryMockId++,
    ctdo_period: '01-31 November 2025',
    ctdo_supervisor_notes: 'Pending approval.',
    ctdo_status: 'for review',
    rows: [
      {
        id: 2,
        days_of_the_week: 'Wednesday',
        work_date: '2025-07-09',
        time_start: '8:12',
        time_end: '18:00',
        accomplishment: 'Client presentation.',
        authorized_claim: 'COC',
      },
      {
        id: 3,
        days_of_the_week: 'Thursday',
        work_date: '2025-07-10',
        time_start: '09:30',
        time_end: '16:00',
        accomplishment: 'Documentation updates.',
        authorized_claim: 'COC',
      },
    ],
    created_at: '2025-07-05',
    updated_at: '2025-07-05',
  },
  {
    id: compensatoryMockId++,
    ctdo_period: '01-30 October 2025',
    ctdo_supervisor_notes: 'Requires additional documentation.',
    ctdo_status: 'approved',
    rows: [
      {
        id: 4,
        days_of_the_week: 'Friday',
        work_date: '2025-07-18',
        time_start: '08:46',
        time_end: '15:00',
        accomplishment: 'Site inspection.',
        authorized_claim: 'COC',
      },
      {
        id: 5,
        days_of_the_week: 'Saturday',
        work_date: '2025-07-19',
        time_start: '08:27',
        time_end: '15:00',
        accomplishment: 'Site inspection.',
        authorized_claim: 'COC',
      },
    ],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
]

/* ApplicationLeave */
// Use a local mockId for compensatorymockData
let applicationLeaveMockId = 1
export const applicationLeavemockData = [
  {
    id: applicationLeaveMockId++,
    employee_id: employee_data[0],
    leave_type_id: {
      id: 3,
      title: 'SICK LEAVE',
      description: 'Sec. 43, Rule XVI, Omnibus Rules Implementing E.O. No. 292',
    },
    date_of_filing: '2025-06-01',
    others_notes: 'Medical leave',
    number_of_days: '2',
    detail_of_leave: 'Fever',
    specific_detail: 'High fever and fatigue',
    commutation: 'yes',
    status: 'for review',
    division_head_disapproval_notes: null,
    days_with_pay: '2',
    days_without_pay: '0',
    disapproved_notes: null,
    dates: [
      {
        id: 1,
        leave_application_id: null,
        start_date: '2025-06-05',
        end_date: '2025-06-06',
      },
    ],
  },
  {
    id: applicationLeaveMockId++,
    employee_id: employee_data[1],
    leave_type_id: {
      id: 6,
      title: 'SPECIAL PRIVILEGE LEAVE',
      description: 'Sec. 21, Rule XVI, Omnibus Rules Implementing E.O. No. 292',
    },
    date_of_filing: '2025-05-15',
    others_notes: 'Family vacation',
    number_of_days: '5',
    detail_of_leave: 'Family trip',
    specific_detail: 'Traveling to hometown',
    commutation: 'no',
    status: 'for review',
    division_head_disapproval_notes: null,
    days_with_pay: '5',
    days_without_pay: '0',
    disapproved_notes: null,
    dates: [
      {
        id: 2,
        leave_application_id: null,
        start_date: '2025-06-10',
        end_date: '2025-06-14',
      },
      {
        id: 5,
        leave_application_id: null,
        start_date: '2025-06-10',
        end_date: '2025-06-14',
      },
    ],
  },
  {
    id: applicationLeaveMockId++,
    employee_id: employee_data[2],
    leave_type_id: {
      id: 7,
      title: 'SOLO PARENT LEAVE',
      description: 'Sec. 21, Rule XVI, Omnibus Rules Implementing E.O. No. 292',
    },
    date_of_filing: '2025-06-02',
    others_notes: 'Flu symptoms',
    number_of_days: '3',
    detail_of_leave: 'Flu',
    specific_detail: 'Cough and fever',
    commutation: 'yes',
    status: 'approved',
    division_head_disapproval_notes: null,
    days_with_pay: '3',
    days_without_pay: '0',
    disapproved_notes: null,
    dates: [
      {
        id: 3,
        leave_application_id: null,
        start_date: '2025-06-07',
        end_date: '2025-06-09',
      },
    ],
  },
]
/* Leave Credits */
// Use a local mockId for leavecreditsmockData
let leaveCreditsMockId = 1
export const leavecreditsmockData = [
  {
    id: leaveCreditsMockId++,
    employee_id: employee_data[0],
    type: 'Sick Leave',
    particular: 'Medical ',
    ut_w_pay_day: '0',
    ut_w_pay_hr: '2',
    ut_w_pay_min: '30',
    ut_day: '0',
    ut_hr: '2',
    ut_min: '30',
    ut_w_pay: '2.5',
    earned: '15', // annual entitlement
    balance: '12.5', // after use
    ut_wo_pay: '0',
    salary: '46,725',
    aca_pera: '2,000',
    leave_credits_dates: [
      {
        id: 1,
        leave_credits_id: null,
        start_date: '2025-06-05',
        end_date: '2025-06-05',
      },
    ],
  },
  {
    id: leaveCreditsMockId++,
    employee_id: employee_data[1],
    type: 'Vacation Leave',
    particular: 'Family vacation',
    ut_w_pay_day: '3',
    ut_w_pay_hr: '0',
    ut_w_pay_min: '0',
    ut_day: '3',
    ut_hr: '0',
    ut_min: '0',
    ut_w_pay: '3',
    earned: '15',
    balance: '12',
    ut_wo_pay: '0',
    salary: '46,725',
    aca_pera: '2,000',
    leave_credits_dates: [
      {
        id: 2,
        leave_credits_id: null,
        start_date: '2025-06-11',
        end_date: '2025-06-14',
      },
      {
        id: 5,
        leave_credits_id: null,
        start_date: '2025-06-16',
        end_date: '2025-06-16',
      },
    ],
  },
  {
    id: leaveCreditsMockId++,
    employee_id: employee_data[2],
    type: 'Sick Leave',
    particular: 'Flu with fever',
    ut_w_pay_day: '2',
    ut_w_pay_hr: '0',
    ut_w_pay_min: '0',
    ut_day: '2',
    ut_hr: '0',
    ut_min: '0',
    ut_w_pay: '2',
    earned: '15',
    balance: '10',
    ut_wo_pay: '0',
    salary: '46,725',
    aca_pera: '2,000',
    leave_credits_dates: [
      {
        id: 3,
        leave_credits_id: null,
        start_date: '2025-06-07',
        end_date: '2025-06-09',
      },
    ],
  },
]

/* Daily Time Records */
// Use a local mockId for dailyTimeRecordsmockData
let dailyTimeRecordsMockId = 1
export const dailyTimeRecordsmockData = [
  {
    id: dailyTimeRecordsMockId++,
    date: '2025-06-05',
    ut: null,
    is_edit_ut: null,
    ot: null,
    is_missing: null,
    employee_remarks: null,
    hr_remarks: null,
    status: 'approved',
    warm_bodies: [
      {
        id: 101,
        employee_id: employee_data[0],
        timestamp: '2025-06-05T07:59:00', // IN 1 (morning)
        daily_time_record_id: 1,
        is_in: true,
      },
      {
        id: 102,
        employee_id: employee_data[0],
        timestamp: '2025-06-05T10:00:00', // OUT 1 (lunch out)
        daily_time_record_id: 1,
        is_in: false,
      },
      {
        id: 103,
        employee_id: employee_data[0],
        timestamp: '2025-06-05T13:00:00', // IN 2 (after lunch)
        daily_time_record_id: 1,
        is_in: true,
      },
      {
        id: 104,
        employee_id: employee_data[0],
        timestamp: '2025-06-05T15:01:00', // OUT 2 (end of day)
        daily_time_record_id: 1,
        is_in: false,
      },
      {
        id: 105,
        employee_id: employee_data[0],
        timestamp: '2025-06-05T17:01:00', // OUT 2 (end of day)
        daily_time_record_id: 1,
        is_in: true,
      },
      {
        id: 106,
        employee_id: employee_data[0],
        timestamp: '2025-05-05T18:01:00', // OUT 2 (end of day)
        daily_time_record_id: 1,
        is_in: false,
      },
    ],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: dailyTimeRecordsMockId++,
    date: '2025-05-10',
    ut: null,
    is_edit_ut: null,
    ot: null,
    is_missing: null,
    employee_remarks: null,
    hr_remarks: null,
    status: 'approved',
    warm_bodies: [
      {
        id: 201,
        employee_id: employee_data[1],
        timestamp: '2025-05-10T08:30:00',
        daily_time_record_id: 2,
        is_in: true,
      },
      {
        id: 202,
        employee_id: employee_data[1],
        timestamp: '2025-05-10T12:30:00',
        daily_time_record_id: 2,
        is_in: false,
      },
      {
        id: 203,
        employee_id: employee_data[1],
        timestamp: '2025-05-10T12:45:00',
        daily_time_record_id: 2,
        is_in: true,
      },
      {
        id: 204,
        employee_id: employee_data[1],
        timestamp: '2025-05-10T17:00:00',
        daily_time_record_id: 2,
        is_in: false,
      },
    ],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: dailyTimeRecordsMockId++,
    date: '2025-06-07',
    ut: null,
    is_edit_ut: null,
    ot: null,
    is_missing: null,
    employee_remarks: null,
    hr_remarks: null,
    status: 'approved',
    warm_bodies: [
      {
        id: 301,
        employee_id: employee_data[2],
        timestamp: '2025-06-07T08:00:00',
        daily_time_record_id: 3,
        is_in: true,
      },
      {
        id: 302,
        employee_id: employee_data[2],
        timestamp: '2025-06-09T17:00:00',
        daily_time_record_id: 3,
        is_in: false,
      },
    ],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: dailyTimeRecordsMockId++,
    date: '2025-06-15',
    ut: null,
    is_edit_ut: null,
    ot: null,
    is_missing: null,
    employee_remarks: null,
    hr_remarks: null,
    status: 'pending',
    warm_bodies: [
      {
        id: 401,
        employee_id: employee_data[2],
        timestamp: '2025-06-15T08:15:00',
        daily_time_record_id: 4,
        is_in: true,
      },
      {
        id: 402,
        employee_id: employee_data[2],
        timestamp: '2025-06-15T12:45:00',
        daily_time_record_id: 4,
        is_in: false,
      },
      {
        id: 403,
        employee_id: employee_data[2],
        timestamp: '2025-06-15T13:00:00',
        daily_time_record_id: 4,
        is_in: true,
      },
      {
        id: 404,
        employee_id: employee_data[2],
        timestamp: '2025-06-15T17:10:00',
        daily_time_record_id: 4,
        is_in: false,
      },
    ],
    created_at: '2025-07-07',
    updated_at: '2025-07-07',
  },
  {
    id: dailyTimeRecordsMockId++,
    date: '2025-06-20',
    ut: null,
    is_edit_ut: null,
    ot: null,
    is_missing: null,
    employee_remarks: null,
    hr_remarks: null,
    status: 'approved',
    warm_bodies: [
      {
        id: 501,
        employee_id: employee_data[3],
        timestamp: '2025-06-20T07:50:00',
        daily_time_record_id: 5,
        is_in: true,
      },
      {
        id: 502,
        employee_id: employee_data[3],
        timestamp: '2025-06-20T12:30:00',
        daily_time_record_id: 5,
        is_in: false,
      },
      {
        id: 503,
        employee_id: employee_data[3],
        timestamp: '2025-06-20T13:45:00',
        daily_time_record_id: 5,
        is_in: true,
      },
      {
        id: 504,
        employee_id: employee_data[3],
        timestamp: '2025-06-20T17:00:00',
        daily_time_record_id: 5,
        is_in: false,
      },
    ],
    created_at: '2025-07-07',
    updated_at: '2025-07-07',
  },
]

/* Selection of DeductionTypes */
export const deductionTypes = [
  { id: 1, label: 'ACA/ PERA' },
  { id: 2, label: 'GSIS EE Share' },
  { id: 3, label: 'Withholding Tax' },
  { id: 4, label: 'GSIS Emergency Loan' },
  { id: 5, label: 'GSIS Conso Loan' },
  { id: 6, label: 'GFAL' },
  { id: 7, label: 'GSIS Policy Loan' },
  { id: 8, label: 'GSIS MPLite' },
  { id: 9, label: 'GSIS MPL' },
  { id: 10, label: 'PHIC Contribution' },
  { id: 11, label: 'GSIS Computer Loan' },
  { id: 12, label: 'Pag-IBIG MPL' },
  { id: 13, label: 'Pag-IBIG Contribution' },
  { id: 14, label: 'Pag-IBIG II' },
  { id: 15, label: 'Pag-IBIG Cal. Loan' },
  { id: 16, label: 'MBA Contribution' },
  { id: 17, label: 'Pag-IBIG HLoan' },
  { id: 18, label: 'COOP Emergency Loan' },
  { id: 19, label: 'MBA Loan' },
  { id: 20, label: 'COOP Share Capital' },
  { id: 21, label: 'COOP Fast Cash' },
  { id: 22, label: 'COOP Educ Loan' },
  { id: 23, label: 'COOP Regular Loan' },
  { id: 24, label: 'COOP C19 RPL' },
  { id: 25, label: 'COOP AWSPL' },
  { id: 26, label: 'COOP Disaster Loan' },
  { id: 27, label: 'SWEAP Dues' },
  { id: 28, label: 'LBP Loan' },
]
