/** MOCK DATA */
let mockId = 1
const individual_basic_details = [
  {
    id: 1,
    first_name: 'Maria',
    last_name: 'Reyes',
    middle_name: 'Lopez',
    ext_name: null,
    birthday: '1985-08-22',
    sex: 'Female',
    place_of_birth: 'Manila',
    civil_status: 'Married',
    height: 160,
    weight: 55,
    blood_type: 'A+',
    gsis_no: '2233445566',
    pag_ibig_no: '6677889900',
    philhealth_no: '5566778899',
    sss_no: '1122334455',
    tin: '234-567-890',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 2,
    first_name: 'Carlos',
    last_name: 'Garcia',
    middle_name: 'Torres',
    ext_name: null,
    birthday: '1992-11-05',
    sex: 'Male',
    place_of_birth: 'Cebu City',
    civil_status: 'Single',
    height: 175,
    weight: 72,
    blood_type: 'B+',
    gsis_no: '9988776655',
    pag_ibig_no: '1122112211',
    philhealth_no: '2233223322',
    sss_no: '5566778899',
    tin: '345-678-901',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 3,
    first_name: 'Ana',
    last_name: 'Santos',
    middle_name: 'Diaz',
    ext_name: null,
    birthday: '1996-02-10',
    sex: 'Female',
    place_of_birth: 'Davao City',
    civil_status: 'Single',
    height: 165,
    weight: 60,
    blood_type: 'AB+',
    gsis_no: '3344556677',
    pag_ibig_no: '4455667788',
    philhealth_no: '6677889900',
    sss_no: '7788990011',
    tin: '456-789-012',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 4,
    first_name: 'Roberto',
    last_name: 'Tan',
    middle_name: 'Villanueva',
    ext_name: null,
    birthday: '1988-09-30',
    sex: 'Male',
    place_of_birth: 'Baguio City',
    civil_status: 'Married',
    height: 168,
    weight: 70,
    blood_type: 'O-',
    gsis_no: '7766554433',
    pag_ibig_no: '2211334455',
    philhealth_no: '3344556677',
    sss_no: '8899001122',
    tin: '567-890-123',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
  {
    id: 5,
    first_name: 'Emily',
    last_name: 'Navarro',
    middle_name: 'Padilla',
    ext_name: null,
    birthday: '1993-03-18',
    sex: 'Female',
    place_of_birth: 'Pasig City',
    civil_status: 'Single',
    height: 158,
    weight: 52,
    blood_type: 'A-',
    gsis_no: '6655443322',
    pag_ibig_no: '9988776655',
    philhealth_no: '7788990011',
    sss_no: '6677889900',
    tin: '678-901-234',
    citizenship: 'Filipino',
    citizenship_acquisition: 'By birth',
    individual_address: null,
    individual_contact_info: null,
    employee: null,
  },
]

const item_id = {
  id: 501,
  number: 'ITEM-501',
  date_of_creation: '2020-01-01',
  status: 'Active',
  date_filled_up: '2020-03-01',
  fund_source_id: {
    id: 1,
    name: 'General Fund',
    created_at: '2020-01-01',
    updated_at: '2020-01-01',
  },
  employment_status: 'Permanent',
  position_id: {
    id: 1,
    title: 'Administrative Officer III',
    parenthetical_title: null,
    level: null,
    created_at: '2020-01-01',
    updated_at: '2020-01-01',
  },
  created_at: '2020-01-01',
  updated_at: '2020-01-01',
}
const employee_data = [
  {
    id: 1,
    individual_basic_detail_id: individual_basic_details[0],
    id_number: 'EMP-2025-001',
    item_id: item_id,
    salary_grade_id: 12,
    position: 'Administrative Officer III',
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000123',
    office_id: 10,
    division_id: {
      id: 3,
      name: 'FINANCE AND MANAGEMENT DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 5,
      name: 'ACCOUNTING SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 2,
    individual_basic_detail_id: individual_basic_details[1],
    id_number: 'EMP-2025-002',
    item_id: item_id,
    salary_grade_id: 15,
    position: 'Human Resource Assistant',
    fund_source: {
      id: 2,
      name: 'Special Education Fund',
    },
    agency_employee_no: 'AGY-000124',
    office_id: 11,
    division_id: {
      id: 4,
      name: 'HUMAN RESOURCE DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 6,
      name: 'RECRUITMENT SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 3,
    individual_basic_detail_id: individual_basic_details[2],
    id_number: 'EMP-2025-003',
    item_id: item_id,
    salary_grade_id: 10,
    position: 'IT Support Specialist',
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000125',
    office_id: 12,
    division_id: {
      id: 5,
      name: 'INFORMATION TECHNOLOGY DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 7,
      name: 'TECHNICAL SUPPORT SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 4,
    individual_basic_detail_id: individual_basic_details[3],
    id_number: 'EMP-2025-004',
    item_id: item_id,
    salary_grade_id: 9,
    position: 'Records Officer',
    fund_source: {
      id: 3,
      name: 'Trust Fund',
    },
    agency_employee_no: 'AGY-000126',
    office_id: 13,
    division_id: {
      id: 6,
      name: 'ADMINISTRATIVE DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 8,
      name: 'RECORDS SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 5,
    individual_basic_detail_id: individual_basic_details[4],
    id_number: 'EMP-2025-005',
    item_id: item_id,
    salary_grade_id: 18,
    position: 'Budget Analyst',
    fund_source: {
      id: 1,
      name: 'General Fund',
    },
    agency_employee_no: 'AGY-000127',
    office_id: 14,
    division_id: {
      id: 7,
      name: 'BUDGET DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 9,
      name: 'BUDGET MONITORING SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
  {
    id: 6,
    individual_basic_detail_id: individual_basic_details[5],
    id_number: 'EMP-2025-006',
    item_id: item_id,
    salary_grade_id: 11,
    position: 'Procurement Officer',
    fund_source: {
      id: 2,
      name: 'Special Education Fund',
    },
    agency_employee_no: 'AGY-000128',
    office_id: 15,
    division_id: {
      id: 8,
      name: 'SUPPLY AND PROCUREMENT DIVISION',
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
    section_or_unit_id: {
      id: 10,
      name: 'SUPPLY SECTION',
      division_id: null,
      head_user_id: null,
      added_by_user_id: null,
      last_modified_by_user_id: null,
    },
  },
]

const payrollDeductions = [
  {
    id: 1,
    amount: 2000,
    range: '1st Half',
    deduction_id: {
      id: 10,
      name: 'PHIC Contribution',
      code: 'PH001',
      details: 'Monthly PhilHealth contribution',
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: 2,
    amount: 3000,
    range: '2nd Half',
    deduction_id: {
      id: 12,
      name: 'Pag-IBIG MPL',
      code: 'PG002',
      details: 'PAG-IBIG monthly deduction',
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: 3,
    amount: 3000,
    range: '2nd Half',
    deduction_id: {
      id: 2,
      name: 'GSIS EE Share',
      code: 'PG002',
      details: 'PAG-IBIG monthly deduction',
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
  {
    id: 4,
    amount: 3000,
    range: '2nd Half',
    deduction_id: {
      id: 12,
      name: 'COOP Emergency Loan',
      code: 'PG002',
      details: 'PAG-IBIG monthly deduction',
      created_at: '2025-01-01T00:00:00Z',
      updated_at: '2025-01-01T00:00:00Z',
    },
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
  },
]

export const payrollMockData = [
  {
    id: mockId++,
    period: '2025-05-01, 2025-05-15',
    gross_monthly_salary: '50000',
    net_pay: '40000',
    total_deductions_1st_half: '5000',
    amount_earned_1st_half: '20000',
    total_deductions_2nd_half: '5000',
    amount_earned_2nd_half: '20000',
    total_deductions_whole: '10000',
    amount_earned_whole: '40000',
    payroll_deduction_id: payrollDeductions,
    employee_id: employee_data[0],
    created_at: '2025-07-06',
    updated_at: '2025-07-06',
    deleted_at: '2025-07-06',
  },
  {
    id: mockId++,
    period: '2025-05-16, 2025-05-31',
    gross_monthly_salary: '48000',
    net_pay: '38000',
    total_deductions_1st_half: '4000',
    amount_earned_1st_half: '19000',
    total_deductions_2nd_half: '6000',
    amount_earned_2nd_half: '19000',
    total_deductions_whole: '10000',
    amount_earned_whole: '38000',
    payroll_deduction_id: payrollDeductions.slice(0, 3),
    employee_id: employee_data[1],
    created_at: '2025-07-07',
    updated_at: '2025-07-07',
    deleted_at: '2025-07-07',
  },
  {
    id: mockId++,
    period: '2025-06-01, 2025-06-15',
    gross_monthly_salary: '52000',
    net_pay: '41000',
    total_deductions_1st_half: '5000',
    amount_earned_1st_half: '21000',
    total_deductions_2nd_half: '5000',
    amount_earned_2nd_half: '20000',
    total_deductions_whole: '10000',
    amount_earned_whole: '41000',
    payroll_deduction_id: payrollDeductions.slice(1, 4),
    employee_id: employee_data[2],
    created_at: '2025-07-08',
    updated_at: '2025-07-08',
    deleted_at: '2025-07-08',
  },
  {
    id: mockId++,
    period: '2025-06-16, 2025-06-30',
    gross_monthly_salary: '55000',
    net_pay: '43000',
    total_deductions_1st_half: '6000',
    amount_earned_1st_half: '22000',
    total_deductions_2nd_half: '6000',
    amount_earned_2nd_half: '21000',
    total_deductions_whole: '12000',
    amount_earned_whole: '43000',
    payroll_deduction_id: payrollDeductions.slice(0, 2),
    employee_id: employee_data[3],
    created_at: '2025-07-09',
    updated_at: '2025-07-09',
    deleted_at: '2025-07-09',
  },
  {
    id: mockId++,
    period: '2025-07-01, 2025-07-15',
    gross_monthly_salary: '47000',
    net_pay: '37000',
    total_deductions_1st_half: '5000',
    amount_earned_1st_half: '18000',
    total_deductions_2nd_half: '5000',
    amount_earned_2nd_half: '19000',
    total_deductions_whole: '10000',
    amount_earned_whole: '37000',
    payroll_deduction_id: payrollDeductions.slice(2, 4),
    employee_id: employee_data[4],
    created_at: '2025-07-10',
    updated_at: '2025-07-10',
    deleted_at: '2025-07-10',
  },
]

/* Selection of DeductionTypes */
export const deductionTypes = [
  { id: 1, label: 'ACA/ PERA' },
  { id: 2, label: 'GSIS EE Share' },
  { id: 3, label: 'Withholding Tax' },
  { id: 4, label: 'GSIS Emergency Loan' },
  { id: 5, label: 'GSIS Conso Loan' },
  { id: 6, label: 'GFAL' },
  { id: 7, label: 'GSIS Policy Loan' },
  { id: 8, label: 'GSIS MPLite' },
  { id: 9, label: 'GSIS MPL' },
  { id: 10, label: 'PHIC Contribution' },
  { id: 11, label: 'GSIS Computer Loan' },
  { id: 12, label: 'Pag-IBIG MPL' },
  { id: 13, label: 'Pag-IBIG Contribution' },
  { id: 14, label: 'Pag-IBIG II' },
  { id: 15, label: 'Pag-IBIG Cal. Loan' },
  { id: 16, label: 'MBA Contribution' },
  { id: 17, label: 'Pag-IBIG HLoan' },
  { id: 18, label: 'COOP Emergency Loan' },
  { id: 19, label: 'MBA Loan' },
  { id: 20, label: 'COOP Share Capital' },
  { id: 21, label: 'COOP Fast Cash' },
  { id: 22, label: 'COOP Educ Loan' },
  { id: 23, label: 'COOP Regular Loan' },
  { id: 24, label: 'COOP C19 RPL' },
  { id: 25, label: 'COOP AWSPL' },
  { id: 26, label: 'COOP Disaster Loan' },
  { id: 27, label: 'SWEAP Dues' },
  { id: 28, label: 'LBP Loan' },
]
